package models

import "time"

// Alert represents a security alert generated by detection rules
type Alert struct {
	AlertID     string           `json:"alert_id" bson:"_id"`
	Timestamp   time.Time        `json:"timestamp" bson:"timestamp"`
	TenantID    string           `json:"tenant_id" bson:"tenant_id"`
	Rule        AlertRule        `json:"rule" bson:"rule"`
	Severity    string           `json:"severity" bson:"severity"`
	Priority    int              `json:"priority" bson:"priority"`
	RiskScore   int              `json:"risk_score" bson:"risk_score"`
	Confidence  float64          `json:"confidence" bson:"confidence"`
	Status      string           `json:"status" bson:"status"`
	Disposition string           `json:"disposition,omitempty" bson:"disposition,omitempty"`
	Title       string           `json:"title" bson:"title"`
	Description string           `json:"description" bson:"description"`
	Entities    AlertEntities    `json:"entities" bson:"entities"`
	Events      AlertEvents      `json:"events" bson:"events"`
	Enrichment  *AlertEnrichment `json:"enrichment,omitempty" bson:"enrichment,omitempty"`
	Response    *AlertResponse   `json:"response,omitempty" bson:"response,omitempty"`
	Assignment  *Assignment      `json:"assignment,omitempty" bson:"assignment,omitempty"`
	SLA         *SLA             `json:"sla,omitempty" bson:"sla,omitempty"`
	Investigation *Investigation `json:"investigation,omitempty" bson:"investigation,omitempty"`
	RelatedAlerts []string       `json:"related_alerts,omitempty" bson:"related_alerts,omitempty"`
	IncidentID    string         `json:"incident_id,omitempty" bson:"incident_id,omitempty"`
	Notifications *Notifications `json:"notifications,omitempty" bson:"notifications,omitempty"`
	Metadata      AlertMetadata  `json:"metadata" bson:"metadata"`
	CreatedAt     time.Time      `json:"created_at" bson:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at" bson:"updated_at"`
}

type AlertRule struct {
	ID         string   `json:"id" bson:"id"`
	Name       string   `json:"name" bson:"name"`
	Version    string   `json:"version" bson:"version"`
	Type       string   `json:"type" bson:"type"`
	Category   string   `json:"category" bson:"category"`
	Framework  string   `json:"framework,omitempty" bson:"framework,omitempty"`
	Tactics    []string `json:"tactics,omitempty" bson:"tactics,omitempty"`
	Techniques []string `json:"techniques,omitempty" bson:"techniques,omitempty"`
}

type AlertEntities struct {
	SourceIPs      []string `json:"source_ips,omitempty" bson:"source_ips,omitempty"`
	DestinationIPs []string `json:"destination_ips,omitempty" bson:"destination_ips,omitempty"`
	Users          []string `json:"users,omitempty" bson:"users,omitempty"`
	Hosts          []string `json:"hosts,omitempty" bson:"hosts,omitempty"`
	Files          []string `json:"files,omitempty" bson:"files,omitempty"`
	Processes      []string `json:"processes,omitempty" bson:"processes,omitempty"`
}

type AlertEvents struct {
	Count          int       `json:"count" bson:"count"`
	EventIDs       []string  `json:"event_ids" bson:"event_ids"`
	FirstEventTime time.Time `json:"first_event_time" bson:"first_event_time"`
	LastEventTime  time.Time `json:"last_event_time" bson:"last_event_time"`
	Timeframe      string    `json:"timeframe" bson:"timeframe"`
}

type AlertEnrichment struct {
	ThreatIntel *ThreatIntelEnrichment `json:"threat_intel,omitempty" bson:"threat_intel,omitempty"`
	AssetImpact *AssetImpactEnrichment `json:"asset_impact,omitempty" bson:"asset_impact,omitempty"`
}

type ThreatIntelEnrichment struct {
	IsMalicious     bool     `json:"is_malicious" bson:"is_malicious"`
	ReputationScore int      `json:"reputation_score" bson:"reputation_score"`
	Categories      []string `json:"categories,omitempty" bson:"categories,omitempty"`
	Sources         []string `json:"sources,omitempty" bson:"sources,omitempty"`
}

type AssetImpactEnrichment struct {
	Criticality      string   `json:"criticality" bson:"criticality"`
	AffectedServices []string `json:"affected_services,omitempty" bson:"affected_services,omitempty"`
	PotentialExposure string  `json:"potential_exposure,omitempty" bson:"potential_exposure,omitempty"`
}

type AlertResponse struct {
	AutoActions     []string `json:"auto_actions,omitempty" bson:"auto_actions,omitempty"`
	PlaybookID      string   `json:"playbook_id,omitempty" bson:"playbook_id,omitempty"`
	PlaybookStatus  string   `json:"playbook_status,omitempty" bson:"playbook_status,omitempty"`
	BlockedIPs      []string `json:"blocked_ips,omitempty" bson:"blocked_ips,omitempty"`
}

type Assignment struct {
	AssignedTo string    `json:"assigned_to,omitempty" bson:"assigned_to,omitempty"`
	AssignedAt time.Time `json:"assigned_at,omitempty" bson:"assigned_at,omitempty"`
	Team       string    `json:"team,omitempty" bson:"team,omitempty"`
}

type SLA struct {
	AcknowledgeBy time.Time `json:"acknowledge_by" bson:"acknowledge_by"`
	ResolveBy     time.Time `json:"resolve_by" bson:"resolve_by"`
	SLABreached   bool      `json:"sla_breached" bson:"sla_breached"`
}

type Investigation struct {
	Notes    string              `json:"notes,omitempty" bson:"notes,omitempty"`
	Evidence []string            `json:"evidence,omitempty" bson:"evidence,omitempty"`
	Timeline []InvestigationStep `json:"timeline,omitempty" bson:"timeline,omitempty"`
}

type InvestigationStep struct {
	Timestamp time.Time `json:"timestamp" bson:"timestamp"`
	Action    string    `json:"action" bson:"action"`
	User      string    `json:"user" bson:"user"`
	Notes     string    `json:"notes,omitempty" bson:"notes,omitempty"`
}

type Notifications struct {
	Channels []string  `json:"channels,omitempty" bson:"channels,omitempty"`
	SentTo   []string  `json:"sent_to,omitempty" bson:"sent_to,omitempty"`
	SentAt   time.Time `json:"sent_at,omitempty" bson:"sent_at,omitempty"`
}

type AlertMetadata struct {
	Tags         []string               `json:"tags,omitempty" bson:"tags,omitempty"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty" bson:"custom_fields,omitempty"`
}
